In [1]:
## English Premier League Predictions

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Importing the data set

matches = pd.read_csv("matches.csv", index_col=0,delimiter=";")
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,13/08/2023,14.0,Premier League,Matchweek 1,Sun,Away,D,2.0,2.0,Brentford,...,Match Report,NaN,18.00,6.0,19.06,0.0,0,0,2024,Tottenham Hotspur
1,19/08/2023,17.3,Premier League,Matchweek 2,Sat,Home,W,2.0,0.0,Manchester Utd,...,Match Report,NaN,17.00,6.0,13.08,0.0,0,0,2024,Tottenham Hotspur
2,26/08/2023,12.3,Premier League,Matchweek 3,Sat,Away,W,2.0,0.0,Bournemouth,...,Match Report,NaN,17.00,6.0,16.06,1.0,0,0,2024,Tottenham Hotspur
4,02/09/2023,15.0,Premier League,Matchweek 4,Sat,Away,W,5.0,2.0,Burnley,...,Match Report,NaN,21.00,11.0,19.03,0.0,0,0,2024,Tottenham Hotspur
5,16/09/2023,15.0,Premier League,Matchweek 5,Sat,Home,W,2.0,1.0,Sheffield Utd,...,Match Report,NaN,28.00.00,10.0,16.04,0.0,0,0,2024,Tottenham Hotspur

In [4]:
matches.shape

(1700, 27)

In [5]:
## To check if we have any missing data.

matches["team"].value_counts()

Tottenham Hotspur           85
West Ham United             85
Everton                     85
Brentford                   85
Manchester City             85
Wolverhampton Wanderers     85
Crystal Palace              85
Chelsea                     85
Manchester United           85
Brighton and Hove Albion    85
Newcastle United            85
Aston Villa                 85
Liverpool                   85
Arsenal                     85
Southampton                 76
Leeds United                76
Leicester City              76
Bournemouth                 47
Fulham                      47
Burnley                     47
Nottingham Forest           47
Watford                     38
Norwich City                38
Sheffield United             9
Luton Town                   9
Name: team, dtype: int64

In [6]:
matches["round"].value_counts()

Matchweek 1     60
Matchweek 3     60
Matchweek 4     60
Matchweek 5     60
Matchweek 6     60
Matchweek 7     60
Matchweek 8     60
Matchweek 9     60
Matchweek 2     60
Matchweek 33    40
Matchweek 26    40
Matchweek 27    40
Matchweek 29    40
Matchweek 30    40
Matchweek 31    40
Matchweek 36    40
Matchweek 34    40
Matchweek 28    40
Matchweek 35    40
Matchweek 24    40
Matchweek 37    40
Matchweek 32    40
Matchweek 25    40
Matchweek 21    40
Matchweek 12    40
Matchweek 23    40
Matchweek 22    40
Matchweek 20    40
Matchweek 19    40
Matchweek 18    40
Matchweek 17    40
Matchweek 16    40
Matchweek 15    40
Matchweek 14    40
Matchweek 13    40
Matchweek 11    40
Matchweek 10    40
Matchweek 38    40
Name: round, dtype: int64

In [7]:
## As we have a data for the 21-22,22-23 & 23-24 season, the maximum number of matches played would be 84, 
# as there has been only 8 matches for this season. At the end of every season, 3 teams are relegated and replaced with 3 new teams.
# Hence, we can say that there are no missing values in the dataset.

In [8]:
## Cleaning the data

In [9]:
matches.dtypes

date             object
time            float64
comp             object
round            object
day              object
venue            object
result           object
gf              float64
ga              float64
opponent         object
xg              float64
xga             float64
poss             object
attendance       object
captain          object
formation        object
referee          object
match report     object
notes           float64
sh               object
sot             float64
dist             object
fk              float64
pk                int64
pkatt             int64
season            int64
team             object
dtype: object

In [10]:
del matches["comp"]

In [11]:
del matches["notes"]

In [12]:
matches["date"] = pd.to_datetime(matches["date"], format='%d/%m/%Y')
matches.dtypes

date            datetime64[ns]
time                   float64
round                   object
day                     object
venue                   object
result                  object
gf                     float64
ga                     float64
opponent                object
xg                     float64
xga                    float64
poss                    object
attendance              object
captain                 object
formation               object
referee                 object
match report            object
sh                      object
sot                    float64
dist                    object
fk                     float64
pk                       int64
pkatt                    int64
season                   int64
team                    object
dtype: object

In [13]:
## Creating categorical values and predictors for Machine Learning.

In [14]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [15]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [16]:
matches["hour"] = matches["time"].astype(str).str.split(':').str[0].astype(float).round().astype(int)

In [17]:
matches["day_code"] = matches["date"].dt.dayofweek

In [18]:
## Setting a target for the model
matches["target"] = (matches["result"] == "W").astype(int)

In [19]:
matches.head()

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
0,2023-08-13,14.0,Matchweek 1,Sun,Away,D,2.0,2.0,Brentford,1.03,...,0.0,0,0,2024,Tottenham Hotspur,0,3,14,6,0
1,2023-08-19,17.3,Matchweek 2,Sat,Home,W,2.0,0.0,Manchester Utd,1.07,...,0.0,0,0,2024,Tottenham Hotspur,1,15,17,5,1
2,2023-08-26,12.3,Matchweek 3,Sat,Away,W,2.0,0.0,Bournemouth,2.01,...,1.0,0,0,2024,Tottenham Hotspur,0,2,12,5,1
4,2023-09-02,15.0,Matchweek 4,Sat,Away,W,5.0,2.0,Burnley,2.02,...,0.0,0,0,2024,Tottenham Hotspur,0,5,15,5,1
5,2023-09-16,15.0,Matchweek 5,Sat,Home,W,2.0,1.0,Sheffield Utd,2.01,...,0.0,0,0,2024,Tottenham Hotspur,1,19,15,5,1

In [20]:
## Building a model

In [21]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [23]:
## Splitting Training and Test Data

In [24]:
train = matches[matches["date"] < '2023-06-01']

In [25]:
test = matches[matches["date"] > '2023-06-01']

In [26]:
predictors = ["venue_code","opp_code","hour","day_code"]

In [27]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [28]:
preds = rf.predict(test[predictors])

In [29]:
## Checking the accuracy of the model

In [30]:
from sklearn.metrics import accuracy_score

In [31]:
error = accuracy_score(test["target"], preds)
error

0.65

In [32]:
combined = pd.DataFrame(dict(actual=test["target"],prediction=preds))

In [33]:
pd.crosstab(index=combined["actual"], columns=combined["prediction"])

prediction   0   1
actual
0           90  19
1           44  27

In [34]:
# In the above output, we can see that when we predicted a loss, we were correct most of the times
# but when we predicted a win, we were incorrect.
# Hence, we would need to update the accuraccy of the model

In [35]:
from sklearn.metrics import precision_score

In [36]:
precision_score(test["target"],preds)

0.5869565217391305

In [37]:
## Creating more predictors to improve the accuracy of the model

In [38]:
grouped_matches = matches.groupby("team")

In [39]:
# To look at 1 team, taking Manchester City as its my favourite.
group = grouped_matches.get_group("Manchester City")
group

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2023-08-11,20.00,Matchweek 1,Fri,Away,W,3.0,0.0,Burnley,1.09,...,0.0,0,0,2024,Manchester City,0,5,20,4,1
3,2023-08-19,20.00,Matchweek 2,Sat,Home,W,1.0,0.0,Newcastle Utd,1.00,...,0.0,0,0,2024,Manchester City,1,16,20,5,1
4,2023-08-27,14.00,Matchweek 3,Sun,Away,W,2.0,1.0,Sheffield Utd,3.05,...,2.0,0,1,2024,Manchester City,0,19,14,6,1
5,2023-09-02,15.00,Matchweek 4,Sat,Home,W,5.0,1.0,Fulham,2.02,...,0.0,1,1,2024,Manchester City,1,9,15,5,1
6,2023-09-16,15.00,Matchweek 5,Sat,Away,W,3.0,1.0,West Ham,3.06,...,1.0,0,0,2024,Manchester City,0,23,15,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,2022-04-30,17.30,Matchweek 35,Sat,Away,W,4.0,0.0,Leeds United,2.04,...,0.0,0,0,2022,Manchester City,0,10,17,5,1
54,2022-05-08,16.30,Matchweek 36,Sun,Home,W,5.0,0.0,Newcastle Utd,3.01,...,1.0,0,0,2022,Manchester City,1,16,16,6,1
55,2022-05-11,20.15,Matchweek 33,Wed,Away,W,5.0,1.0,Wolves,2.03,...,0.0,0,0,2022,Manchester City,0,24,20,2,1
56,2022-05-15,14.00,Matchweek 37,Sun,Away,D,2.0,2.0,West Ham,2.04,...,2.0,0,1,2022,Manchester City,0,23,14,6,0
57,2022-05-22,16.00,Matchweek 38,Sun,Home,W,3.0,2.0,Aston Villa,3.04,...,1.0,0,0,2022,Manchester City,1,1,16,6,1

In [40]:
group = group.copy()  
group['sh'] = pd.to_numeric(group['sh'], errors='coerce')

In [41]:
# Creating a function to calculate rolling averages
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()

    # Check which columns exist in both 'cols' and 'rolling_stats'
    valid_cols = [col for col in new_cols if col in rolling_stats.columns]

    # Create new columns with rolling averages
    group[valid_cols] = rolling_stats[valid_cols]
    group = group.dropna(subset=valid_cols)

    return group

In [42]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

In [43]:
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling']

In [44]:
rolling_averages(group, cols, new_cols)

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2021-08-15,16.3,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham,1.08,...,1.0,0,0,2022,Manchester City,0,21,16,6,0
2,2021-08-21,15.0,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,2.06,...,1.0,0,0,2022,Manchester City,1,17,15,5,1
3,2021-08-28,12.3,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,4.04,...,0.0,0,0,2022,Manchester City,1,0,12,5,1
4,2021-09-11,15.0,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,2.08,...,0.0,0,0,2022,Manchester City,0,11,15,5,1
6,2021-09-18,15.0,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,1.00,...,1.0,0,0,2022,Manchester City,1,20,15,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,2023-09-16,15.0,Matchweek 5,Sat,Away,W,3.0,1.0,West Ham,3.06,...,1.0,0,0,2024,Manchester City,0,23,15,5,1
8,2023-09-23,15.0,Matchweek 6,Sat,Home,W,2.0,0.0,Nott'ham Forest,1.03,...,2.0,0,0,2024,Manchester City,1,18,15,5,1
10,2023-09-30,15.0,Matchweek 7,Sat,Away,L,1.0,2.0,Wolves,0.09,...,1.0,0,0,2024,Manchester City,0,24,15,5,0
12,2023-10-08,16.3,Matchweek 8,Sun,Away,L,0.0,1.0,Arsenal,0.05,...,0.0,0,0,2024,Manchester City,0,0,16,6,0
13,2023-10-21,15.0,Matchweek 9,Sat,Home,W,2.0,1.0,Brighton,0.08,...,1.0,0,0,2024,Manchester City,1,4,15,5,1

In [45]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [46]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [47]:
matches_rolling

                                 date  time        round  day venue result  \
team
Arsenal                 0  2021-08-13  20.0  Matchweek 1  Fri  Away      L
                        1  2021-08-22  16.3  Matchweek 2  Sun  Home      L
                        3  2021-08-28  12.3  Matchweek 3  Sat  Away      L
                        4  2021-09-11  15.0  Matchweek 4  Sat  Home      W
                        5  2021-09-18  15.0  Matchweek 5  Sat  Away      W
...                               ...   ...          ...  ...   ...    ...
Wolverhampton Wanderers 5  2023-09-16  12.3  Matchweek 5  Sat  Home      L
                        6  2023-09-23  15.0  Matchweek 6  Sat  Away      D
                        8  2023-09-30  15.0  Matchweek 7  Sat  Home      W
                        9  2023-10-08  14.0  Matchweek 8  Sun  Home      D
                        10 2023-10-21  15.0  Matchweek 9  Sat  Away      W

                             gf   ga         opponent    xg  ...   fk pk  \
team                                                         ...
Arsenal                 0   0.0  2.0        Brentford  1.03  ...  1.0  0
                        1   0.0  2.0          Chelsea  0.03  ...  0.0  0
                        3   0.0  5.0  Manchester City  0.02  ...  0.0  0
                        4   1.0  0.0     Norwich City  2.07  ...  1.0  0
                        5   1.0  0.0          Burnley  1.01  ...  1.0  0
...                         ...  ...              ...   ...  ...  ... ..
Wolverhampton Wanderers 5   1.0  3.0        Liverpool  0.06  ...  0.0  0
                        6   1.0  1.0       Luton Town  0.06  ...  0.0  0
                        8   2.0  1.0  Manchester City  0.04  ...  0.0  0
                        9   1.0  1.0      Aston Villa  1.07  ...  0.0  0
                        10  2.0  1.0      Bournemouth  2.04  ...  0.0  0

                           pkatt season                     team venue_code  \
team
Arsenal                 0      0   2022                  Arsenal          0
                        1      0   2022                  Arsenal          1
                        3      0   2022                  Arsenal          0
                        4      0   2022                  Arsenal          1
                        5      0   2022                  Arsenal          0
...                          ...    ...                      ...        ...
Wolverhampton Wanderers 5      0   2024  Wolverhampton Wanderers          1
                        6      0   2024  Wolverhampton Wanderers          0
                        8      0   2024  Wolverhampton Wanderers          1
                        9      0   2024  Wolverhampton Wanderers          1
                        10     0   2024  Wolverhampton Wanderers          0

                           opp_code hour  day_code target
team
Arsenal                 0         3   20         4      0
                        1         6   16         6      0
                        3        14   12         5      0
                        4        17   15         5      1
                        5         5   15         5      1
...                             ...  ...       ...    ...
Wolverhampton Wanderers 5        12   12         5      0
                        6        13   15         5      0
                        8        14   15         5      1
                        9         1   14         6      0
                        10        2   15         5      1

[1700 rows x 30 columns]

In [48]:
matches_rolling = matches_rolling.droplevel('team')

In [49]:
# Correcting the index
matches_rolling.index = range(matches_rolling.shape[0])

In [50]:
matches_rolling

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
0,2021-08-13,20.0,Matchweek 1,Fri,Away,L,0.0,2.0,Brentford,1.03,...,1.0,0,0,2022,Arsenal,0,3,20,4,0
1,2021-08-22,16.3,Matchweek 2,Sun,Home,L,0.0,2.0,Chelsea,0.03,...,0.0,0,0,2022,Arsenal,1,6,16,6,0
2,2021-08-28,12.3,Matchweek 3,Sat,Away,L,0.0,5.0,Manchester City,0.02,...,0.0,0,0,2022,Arsenal,0,14,12,5,0
3,2021-09-11,15.0,Matchweek 4,Sat,Home,W,1.0,0.0,Norwich City,2.07,...,1.0,0,0,2022,Arsenal,1,17,15,5,1
4,2021-09-18,15.0,Matchweek 5,Sat,Away,W,1.0,0.0,Burnley,1.01,...,1.0,0,0,2022,Arsenal,0,5,15,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1695,2023-09-16,12.3,Matchweek 5,Sat,Home,L,1.0,3.0,Liverpool,0.06,...,0.0,0,0,2024,Wolverhampton Wanderers,1,12,12,5,0
1696,2023-09-23,15.0,Matchweek 6,Sat,Away,D,1.0,1.0,Luton Town,0.06,...,0.0,0,0,2024,Wolverhampton Wanderers,0,13,15,5,0
1697,2023-09-30,15.0,Matchweek 7,Sat,Home,W,2.0,1.0,Manchester City,0.04,...,0.0,0,0,2024,Wolverhampton Wanderers,1,14,15,5,1
1698,2023-10-08,14.0,Matchweek 8,Sun,Home,D,1.0,1.0,Aston Villa,1.07,...,0.0,0,0,2024,Wolverhampton Wanderers,1,1,14,6,0
1699,2023-10-21,15.0,Matchweek 9,Sat,Away,W,2.0,1.0,Bournemouth,2.04,...,0.0,0,0,2024,Wolverhampton Wanderers,0,2,15,5,1

In [51]:
def make_predictions(data, predictors, target_column):
    # Split the data into training and testing sets
    train = data[data["date"] < '2023-01-01']
    test = data[data["date"] > '2023-01-01']
    
    if not set(predictors).issubset(train.columns):
        missing_columns = list(set(predictors) - set(train.columns))
        raise ValueError(f"Predictors {missing_columns} not found in the DataFrame.")
    
    if target_column not in train.columns:
        raise ValueError(f"Target column '{target_column}' not found in the DataFrame.")
    
    if train.isnull().values.any():
        raise ValueError("There are missing values in the 'train' DataFrame.")
    
    rf = RandomForestClassifier()
    rf.fit(train[predictors].values, train[target_column].values)  # Convert to NumPy arrays
    
    preds = rf.predict(test[predictors].values)  # Convert to NumPy arrays
    
    combined = pd.DataFrame(dict(actual=test[target_column], predicted=preds), index=test.index)
    
    error = precision_score(test[target_column], preds)
    
    return combined, error

target_column = 'target' 
combined, error = make_predictions(matches_rolling, predictors, target_column)

In [52]:
# Define the predictors and target_column for the new dataset
new_predictors = ["venue_code", "opp_code", "hour", "day_code"] 
new_target_column = 'target' 

combined, new_precision = make_predictions(matches_rolling, new_predictors, new_target_column)

# Print the new precision score
print("New Precision Score:", new_precision)

New Precision Score: 0.4519774011299435

In [53]:
## Although, we were unable to increase the precision score, we will continue with the analysis as of now.
# (Will update after checking it)

In [54]:
# Combining the Home and Away data
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [55]:
combined

,actual,predicted,date,team,opponent,result
54,0,0,2023-01-03,Arsenal,Newcastle Utd,D
55,1,0,2023-01-15,Arsenal,Tottenham,W
56,1,0,2023-01-22,Arsenal,Manchester Utd,W
57,0,0,2023-02-04,Arsenal,Everton,L
58,0,0,2023-02-11,Arsenal,Brentford,D
...,...,...,...,...,...,...
1695,0,0,2023-09-16,Wolverhampton Wanderers,Liverpool,L
1696,0,0,2023-09-23,Wolverhampton Wanderers,Luton Town,D
1697,1,0,2023-09-30,Wolverhampton Wanderers,Manchester City,W
1698,0,1,2023-10-08,Wolverhampton Wanderers,Aston Villa,D
1699,1,0,2023-10-21,Wolverhampton Wanderers,Bournemouth,W

In [56]:
# Mapping the names
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton", "Manchester United": "Manchester Utd", "Newcastle United": "Newcastle Utd", "Tottenham Hotspur": "Tottenham", "West Ham United": "West Ham", "Wolverhampton Wanderers": "Wolves"} 
mapping = MissingDict(**map_values)

In [57]:
combined["new_team"] = combined["team"].map(mapping)

In [58]:
combined.head()

    actual  predicted       date     team        opponent result new_team
54       0          0 2023-01-03  Arsenal   Newcastle Utd      D  Arsenal
55       1          0 2023-01-15  Arsenal       Tottenham      W  Arsenal
56       1          0 2023-01-22  Arsenal  Manchester Utd      W  Arsenal
57       0          0 2023-02-04  Arsenal         Everton      L  Arsenal
58       0          0 2023-02-11  Arsenal       Brentford      D  Arsenal

In [59]:
# Merging the data for checking

merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [60]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,0,2023-01-03,Arsenal,Newcastle Utd,D,Arsenal,0,0,Newcastle United,Arsenal,D,Newcastle Utd
1,1,0,2023-01-15,Arsenal,Tottenham,W,Arsenal,0,1,Tottenham Hotspur,Arsenal,L,Tottenham
2,1,0,2023-01-22,Arsenal,Manchester Utd,W,Arsenal,0,0,Manchester United,Arsenal,L,Manchester Utd
3,0,0,2023-02-04,Arsenal,Everton,L,Arsenal,1,0,Everton,Arsenal,W,Everton
4,0,0,2023-02-11,Arsenal,Brentford,D,Arsenal,0,0,Brentford,Arsenal,D,Brentford
...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,0,0,2023-09-16,Wolverhampton Wanderers,Liverpool,L,Wolves,1,1,Liverpool,Wolves,W,Liverpool
565,0,0,2023-09-23,Wolverhampton Wanderers,Luton Town,D,Wolves,0,0,Luton Town,Wolves,D,Luton Town
566,1,0,2023-09-30,Wolverhampton Wanderers,Manchester City,W,Wolves,0,0,Manchester City,Wolves,L,Manchester City
567,0,1,2023-10-08,Wolverhampton Wanderers,Aston Villa,D,Wolves,0,0,Aston Villa,Wolves,D,Aston Villa
568,1,0,2023-10-21,Wolverhampton Wanderers,Bournemouth,W,Wolves,0,0,Bournemouth,Wolves,L,Bournemouth

In [61]:
# To check if the accuracy of the model

merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] ==0)]["actual_x"].value_counts()

0    79
1    68
Name: actual_x, dtype: int64

In [62]:
68 /142

0.4788732394366197

In [63]:
73 + 69

142

In [64]:
## We were able to improve the accuracy of the model 
## When the model predicts a outcome, the possibility of it being correct is 51%

In [65]:
# combined.to_csv('epl_predictions_2023_34.csv', index=False)